# cerebrium.toml
[cerebrium.deployment]
name = "image-classifier-prod"

# This flag is essential for custom Docker image deployment
use_dockerfile = true 

[cerebrium.hardware]
# T4 is a good balance of performance and cost for inference
gpu = "T4" 
memory = 8.0

[cerebrium.scaling]
# Scale to zero when idle to minimize costs on the free plan
min_replicas = 0 

